# Generated by Django 2.2 on 2022-01-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='Заголовок')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('vote_amount', models.IntegerField(default=0, verbose_name='Счетчик голосов')),
                ('author', models.CharField(default='Unknown', max_length=40, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
